In [1]:
import pandas as pd
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
data = {'Name': ['John', 'Alice'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0   John   25
1  Alice   30

In [3]:
print(df.head())

    Name  Age
0   John   25
1  Alice   30

In [4]:
print(df.tail(3))

    Name  Age
0   John   25
1  Alice   30

In [5]:
print(df.columns)
print(df.info())

Index(['Name', 'Age'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes
None

In [6]:
print(df.describe())

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [7]:
print(df['Name'])

0     John
1    Alice
Name: Name, dtype: object

In [8]:
print(df[['Name', 'Age']])

    Name  Age
0   John   25
1  Alice   30

In [9]:
print(df[df['Age'] > 25])

    Name  Age
1  Alice   30

In [10]:
print(df.sort_values(by='Age'))

    Name  Age
0   John   25
1  Alice   30

In [11]:
df['Salary'] = [50000, 60000]
print(df)

    Name  Age  Salary
0   John   25   50000
1  Alice   30   60000

In [12]:
df = df.drop('Salary', axis=1)
print(df)

    Name  Age
0   John   25
1  Alice   30

In [13]:
print(df.isnull())

    Name    Age
0  False  False
1  False  False

In [14]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [15]:
group = df.groupby('Name')['Age'].mean()
print(group)

Name
Alice    30.0
John     25.0
Name: Age, dtype: float64

In [16]:
df.groupby('Name').agg({'Age': ['mean', 'max']})

        Age
       mean max
Name
Alice  30.0  30
John   25.0  25

In [17]:
df1 = pd.DataFrame({'ID':[1,2], 'Name':['A','B']})
df2 = pd.DataFrame({'ID':[1,2], 'Score':[90,80]})
merged = pd.merge(df1, df2, on='ID')
print(merged)

   ID Name  Score
0   1    A     90
1   2    B     80

In [18]:
df3 = pd.concat([df1, df2], axis=0)
print(df3)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
0   1  NaN   90.0
1   2  NaN   80.0

In [19]:
pd.pivot_table(df, values='Age', index='Name', aggfunc='mean')

        Age
Name
Alice  30.0
John   25.0

In [20]:
df.columns = ['Person', 'Years']
print(df)

  Person  Years
0   John     25
1  Alice     30

In [21]:
df = df.reset_index(drop=True)
print(df)

  Person  Years
0   John     25
1  Alice     30

In [24]:
df = df.set_index('person')
print(df)

KeyError: "None of ['person'] are in the columns"

In [25]:
df = df.drop_duplicates()

In [26]:
df['Age'] = df['Age'].astype(float)

KeyError: 'Age'